(base) ubuntu@ip-172-31-17-239:~/LLM4Decompile-test/repo_test/reverse-engineering-learning/LLM4Decompile-Testing$ python compile.py 
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/ubuntu/LLM4Decompile-test/repo_test/reverse-engineering-learning/LLM4Decompile-Testing/compile.py", line 13, in <module>
    subprocess.run(compile_command, shell=True, check=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.13/subprocess.py", line 579, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'gcc -o samples/sample_O0.o samples/sample.c -O0 -lm' returned non-zero exit status 1.
